export const REGIONS = [
  { id: "seoul", name: "수도권" },
  { id: "busan", name: "부산·울산·경남" },
  { id: "daegu", name: "대구·경북" },
  { id: "gwangju", name: "광주·전남" },
  { id: "jeonbuk", name: "전북" },
  { id: "daejeon", name: "대전·세종·충남" },
  { id: "chungbuk", name: "충북" },
  { id: "gangwon", name: "강원" },
  { id: "jeju", name: "제주" },
];

const rawChannels = [
  ["seoul", "KBS 1라디오", "kbs", "1radio"],
  ["seoul", "KBS 2라디오", "kbs", "2radio"],
  ["seoul", "KBS 3라디오", "kbs", "3radio"],
  ["seoul", "KBS 1FM", "kbs", "1fm"],
  ["seoul", "KBS 2FM", "kbs", "2fm"],
  ["seoul", "KBS 한민족방송", "kbs", "hanminjok"],
  ["seoul", "MBC 표준FM", "mbc", "sfm"],
  ["seoul", "MBC FM4U", "mbc", "fm4u"],
  ["seoul", "MBC mini 올댓뮤직", "mbc", "chm"],
  ["seoul", "MBC 보이는 라디오", "mbc", "bora"],
  ["seoul", "SBS 러브FM", "sbs", "lovefm"],
  ["seoul", "SBS 파워FM", "sbs", "powerfm"],
  ["seoul", "SBS 고릴라디오M", "sbs", "dmb"],
  ["seoul", "EBS FM", "ebs", "fm"],
  ["seoul", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["seoul", "OBS 라디오", "obs"],
  ["seoul", "iFM 경인방송", "ifm"],
  ["seoul", "YTN 라디오", "ytn"],
  ["seoul", "TBS FM", "tbs", "fm"],
  ["seoul", "TBS eFM", "tbs", "efm"],
  ["seoul", "TBN 경인교통방송", "tbn"],
  ["seoul", "CBS 표준FM", "cbs", "sfm"],
  ["seoul", "CBS 음악FM", "cbs", "mfm"],
  ["seoul", "CBS JOY4U", "cbs", "joy4u"],
  ["seoul", "FEBC 서울극동방송", "febc"],
  ["seoul", "BBS 서울불교방송", "bbs"],
  ["seoul", "CPBC 가톨릭평화방송", "cpbc"],
  ["seoul", "WBS 서울원음방송", "wbs"],
  ["seoul", "국방FM", "kookbang"],
  ["seoul", "국악방송", "kugak"],
  ["seoul", "AFN FM Humphreys", "afn", undefined, "humphreys"],
  ["seoul", "관악FM", "community", "gwanakfm"],
  ["seoul", "마포FM", "community", "mapofm"],
  ["seoul", "성남FM", "community", "seongnamfm"],
  ["seoul", "서대문FM", "community", "sdmfm"],
  ["seoul", "수원FM", "community", "sonefm"],
  ["seoul", "GO구리FM", "community", "gurifm"],
  ["seoul", "단원FM", "community", "dwfm"],

  ["busan", "KBS부산 1라디오", "kbs", "1radio", "busan"],
  ["busan", "KBS부산 2라디오", "kbs", "2radio", "busan"],
  ["busan", "KBS부산 음악FM", "kbs", "1fm", "busan"],
  ["busan", "KBS울산 1라디오", "kbs", "1radio", "ulsan"],
  ["busan", "KBS창원 1라디오", "kbs", "1radio", "changwon"],
  ["busan", "KBS창원 2라디오", "kbs", "2radio", "changwon"],
  ["busan", "KBS창원 음악FM", "kbs", "1fm", "changwon"],
  ["busan", "KBS진주 1라디오", "kbs", "1radio", "jinju"],
  ["busan", "부산MBC 표준FM", "mbc", "sfm", "busan"],
  ["busan", "부산MBC FM4U", "mbc", "fm4u", "busan"],
  ["busan", "울산MBC 표준FM", "mbc", "sfm", "ulsan"],
  ["busan", "울산MBC FM4U", "mbc", "fm4u", "ulsan"],
  ["busan", "MBC경남 표준FM", "mbc", "sfm", "changwon"],
  ["busan", "MBC경남 FM4U", "mbc", "fm4u", "changwon"],
  ["busan", "KNN 러브FM", "sbs", "lovefm", "busan"],
  ["busan", "KNN 파워FM", "sbs", "powerfm", "busan"],
  ["busan", "UBC 그린FM", "sbs", "powerfm", "ulsan"],
  ["busan", "EBS FM", "ebs", "fm"],
  ["busan", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["busan", "TBN 부산교통방송", "tbn", undefined, "busan"],
  ["busan", "TBN 울산교통방송", "tbn", undefined, "ulsan"],
  ["busan", "TBN 경남교통방송", "tbn", undefined, "gyeongnam"],
  ["busan", "부산CBS 표준FM", "cbs", "sfm", "busan"],
  ["busan", "부산CBS 음악FM", "cbs", "mfm", "busan"],
  ["busan", "울산CBS 표준FM", "cbs", "sfm", "ulsan"],
  ["busan", "경남CBS 표준FM", "cbs", "sfm", "gyeongnam"],
  ["busan", "CBS JOY4U", "cbs", "joy4u"],
  ["busan", "FEBC 부산극동방송", "febc", undefined, "busan"],
  ["busan", "FEBC 울산극동방송", "febc", undefined, "ulsan"],
  ["busan", "FEBC 창원극동방송", "febc", undefined, "changwon"],
  ["busan", "BBS 부산불교방송", "bbs", undefined, "busan"],
  ["busan", "CPBC 부산가톨릭평화방송", "cpbc", undefined, "busan"],
  ["busan", "WBS 부산원음방송", "wbs", undefined, "busan"],
  ["busan", "국방FM", "kookbang"],
  ["busan", "부산영어방송", "befm"],
  ["busan", "연제공동체라디오", "community", "yeonjefm"],
  ["busan", "남해FM", "community", "namhaefm"],

  ["daegu", "KBS대구 1라디오", "kbs", "1radio", "daegu"],
  ["daegu", "KBS대구 2라디오", "kbs", "2radio", "daegu"],
  ["daegu", "KBS대구 음악FM", "kbs", "1fm", "daegu"],
  ["daegu", "KBS안동 1라디오", "kbs", "1radio", "andong"],
  ["daegu", "KBS포항 1라디오", "kbs", "1radio", "pohang"],
  ["daegu", "대구MBC 표준FM", "mbc", "sfm", "daegu"],
  ["daegu", "대구MBC FM4U", "mbc", "fm4u", "daegu"],
  ["daegu", "안동MBC 표준FM", "mbc", "sfm", "andong"],
  ["daegu", "안동MBC FM4U", "mbc", "fm4u", "andong"],
  ["daegu", "포항MBC 표준FM", "mbc", "sfm", "pohang"],
  ["daegu", "포항MBC FM4U", "mbc", "fm4u", "pohang"],
  ["daegu", "TBC 드림FM", "sbs", "powerfm", "daegu"],
  ["daegu", "EBS FM", "ebs", "fm"],
  ["daegu", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["daegu", "TBN 대구교통방송", "tbn", undefined, "daegu"],
  ["daegu", "TBN 경북교통방송", "tbn", undefined, "gyeongbuk"],
  ["daegu", "대구CBS 표준FM", "cbs", "sfm", "daegu"],
  ["daegu", "대구CBS 음악FM", "cbs", "mfm", "daegu"],
  ["daegu", "포항CBS 표준FM", "cbs", "sfm", "pohang"],
  ["daegu", "CBS JOY4U", "cbs", "joy4u"],
  ["daegu", "FEBC 대구극동방송", "febc", undefined, "daegu"],
  ["daegu", "FEBC 포항극동방송", "febc", undefined, "pohang"],
  ["daegu", "BBS 대구불교방송", "bbs", undefined, "daegu"],
  ["daegu", "CPBC 대구가톨릭평화방송", "cpbc", undefined, "daegu"],
  ["daegu", "WBS 대구원음방송", "wbs", undefined, "daegu"],
  ["daegu", "국방FM", "kookbang"],
  ["daegu", "AFN FM Daegu", "afn", undefined, "daegu"],
  ["daegu", "성서공동체FM", "community", "scnfm"],
  ["daegu", "대구동구FM", "community", "daegufm"],
  ["daegu", "영주FM", "community", "yeongjufm"],
  ["daegu", "성주FM", "community", "sjfm"],
  ["daegu", "상주FM", "community", "sangjufm"],

  ["gwangju", "KBS광주 1라디오", "kbs", "1radio", "gwangju"],
  ["gwangju", "KBS광주 2라디오", "kbs", "2radio", "gwangju"],
  ["gwangju", "KBS광주 음악FM", "kbs", "1fm", "gwangju"],
  ["gwangju", "KBS목포 1라디오", "kbs", "1radio", "mokpo"],
  ["gwangju", "KBS목포 음악FM", "kbs", "1fm", "mokpo"],
  ["gwangju", "KBS순천 1라디오", "kbs", "1radio", "suncheon"],
  ["gwangju", "광주MBC 표준FM", "mbc", "sfm", "gwangju"],
  ["gwangju", "광주MBC FM4U", "mbc", "fm4u", "gwangju"],
  ["gwangju", "목포MBC 표준FM", "mbc", "sfm", "mokpo"],
  ["gwangju", "목포MBC FM4U", "mbc", "fm4u", "mokpo"],
  ["gwangju", "여수MBC 표준FM", "mbc", "sfm", "yeosu"],
  ["gwangju", "여수MBC FM4U", "mbc", "fm4u", "yeosu"],
  ["gwangju", "KBC 마이FM", "sbs", "powerfm", "gwangju"],
  ["gwangju", "EBS FM", "ebs", "fm"],
  ["gwangju", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["gwangju", "TBN 광주교통방송", "tbn", undefined, "gwangju"],
  ["gwangju", "광주CBS 표준FM", "cbs", "sfm", "gwangju"],
  ["gwangju", "광주CBS 음악FM", "cbs", "mfm", "gwangju"],
  ["gwangju", "전남CBS 표준FM", "cbs", "sfm", "jeonnam"],
  ["gwangju", "CBS JOY4U", "cbs", "joy4u"],
  ["gwangju", "FEBC 광주극동방송", "febc", undefined, "gwangju"],
  ["gwangju", "FEBC 목포극동방송", "febc", undefined, "mokpo"],
  ["gwangju", "FEBC 전남동부극동방송", "febc", undefined, "jeonnam"],
  ["gwangju", "BBS 광주불교방송", "bbs", undefined, "gwangju"],
  ["gwangju", "CPBC 광주가톨릭평화방송", "cpbc", undefined, "gwangju"],
  ["gwangju", "WBS 광주원음방송", "wbs", undefined, "gwangju"],
  ["gwangju", "국방FM", "kookbang"],
  ["gwangju", "글로벌광주방송", "ggn"],
  ["gwangju", "광주국악방송", "kugak", undefined, "gwangju"],
  ["gwangju", "광주FM", "community", "kjfm"],
  ["gwangju", "GBS고려방송", "community", "crfm"],
  ["gwangju", "순천미디어네트워크", "community", "suncheonfm"],

  ["jeonbuk", "KBS전주 1라디오", "kbs", "1radio", "jeonju"],
  ["jeonbuk", "KBS전주 2라디오", "kbs", "2radio", "jeonju"],
  ["jeonbuk", "KBS전주 음악FM", "kbs", "1fm", "jeonju"],
  ["jeonbuk", "전주MBC 표준FM", "mbc", "sfm", "jeonju"],
  ["jeonbuk", "전주MBC FM4U", "mbc", "fm4u", "jeonju"],
  ["jeonbuk", "JTV 매직FM", "sbs", "powerfm", "jeonju"],
  ["jeonbuk", "EBS FM", "ebs", "fm"],
  ["jeonbuk", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["jeonbuk", "TBN 전북교통방송", "tbn", undefined, "jeonbuk"],
  ["jeonbuk", "전북CBS 표준FM", "cbs", "sfm", "jeonbuk"],
  ["jeonbuk", "CBS JOY4U", "cbs", "joy4u"],
  ["jeonbuk", "FEBC 전북극동방송", "febc", undefined, "jeonbuk"],
  ["jeonbuk", "WBS 전북원음방송", "wbs", undefined, "jeonbuk"],
  ["jeonbuk", "국방FM", "kookbang"],
  ["jeonbuk", "AFN FM Kunsan", "afn", undefined, "kunsan"],
  ["jeonbuk", "전주FM", "community", "jcfm"],

  ["daejeon", "KBS대전 1라디오", "kbs", "1radio", "daejeon"],
  ["daejeon", "KBS대전 2라디오", "kbs", "2radio", "daejeon"],
  ["daejeon", "KBS대전 음악FM", "kbs", "1fm", "daejeon"],
  ["daejeon", "대전MBC 표준FM", "mbc", "sfm", "daejeon"],
  ["daejeon", "대전MBC FM4U", "mbc", "fm4u", "daejeon"],
  ["daejeon", "TJB 파워FM", "sbs", "powerfm", "daejeon"],
  ["daejeon", "EBS FM", "ebs", "fm"],
  ["daejeon", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["daejeon", "TBN 대전교통방송", "tbn", undefined, "daejeon"],
  ["daejeon", "TBN 충남교통방송", "tbn", undefined, "chungnam"],
  ["daejeon", "대전CBS 표준FM", "cbs", "sfm", "daejeon"],
  ["daejeon", "CBS JOY4U", "cbs", "joy4u"],
  ["daejeon", "FEBC 대전극동방송", "febc", undefined, "daejeon"],
  ["daejeon", "국방FM", "kookbang"],
  ["daejeon", "대전국악방송", "kugak", undefined, "daejeon"],
  ["daejeon", "금강FM", "community", "keumkangfm"],
  ["daejeon", "세종FM", "community", "sejongfm"],
  ["daejeon", "한밭FM", "community", "hanbatfm"],

  ["chungbuk", "KBS청주 1라디오", "kbs", "1radio", "cheongju"],
  ["chungbuk", "KBS청주 2라디오", "kbs", "2radio", "cheongju"],
  ["chungbuk", "KBS청주 음악FM", "kbs", "1fm", "cheongju"],
  ["chungbuk", "KBS충주 1라디오", "kbs", "1radio", "chungju"],
  ["chungbuk", "KBS충주 음악FM", "kbs", "1fm", "chungju"],
  ["chungbuk", "MBC충북 표준FM", "mbc", "sfm", "cheongju"],
  ["chungbuk", "MBC충북 FM4U", "mbc", "fm4u", "cheongju"],
  ["chungbuk", "CJB 조이FM", "sbs", "powerfm", "cheongju"],
  ["chungbuk", "EBS FM", "ebs", "fm"],
  ["chungbuk", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["chungbuk", "TBN 충북교통방송", "tbn", undefined, "chungbuk"],
  ["chungbuk", "충북CBS 표준FM", "cbs", "sfm", "cheongju"],
  ["chungbuk", "CBS JOY4U", "cbs", "joy4u"],
  ["chungbuk", "국방FM", "kookbang"],
  ["chungbuk", "옥천FM", "community", "obn"],

  ["gangwon", "KBS춘천 1라디오", "kbs", "1radio", "chuncheon"],
  ["gangwon", "KBS춘천 2라디오", "kbs", "2radio", "chuncheon"],
  ["gangwon", "KBS춘천 음악FM", "kbs", "1fm", "chuncheon"],
  ["gangwon", "KBS강릉 1라디오", "kbs", "1radio", "gangneung"],
  ["gangwon", "KBS강릉 음악FM", "kbs", "1fm", "gangneung"],
  ["gangwon", "KBS원주 1라디오", "kbs", "1radio", "wonju"],
  ["gangwon", "KBS원주 음악FM", "kbs", "1fm", "wonju"],
  ["gangwon", "춘천MBC 표준FM", "mbc", "sfm", "chuncheon"],
  ["gangwon", "춘천MBC FM4U", "mbc", "fm4u", "chuncheon"],
  ["gangwon", "원주MBC 표준FM", "mbc", "sfm", "wonju"],
  ["gangwon", "원주MBC FM4U", "mbc", "fm4u", "wonju"],
  ["gangwon", "MBC강원영동 표준FM", "mbc", "sfm", "gangneung"],
  ["gangwon", "MBC강원영동 FM4U", "mbc", "fm4u", "gangneung"],
  ["gangwon", "G1 프레쉬FM", "sbs", "powerfm", "chuncheon"],
  ["gangwon", "EBS FM", "ebs", "fm"],
  ["gangwon", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["gangwon", "TBN 강원교통방송", "tbn", undefined, "gangwon"],
  ["gangwon", "춘천CBS 표준FM", "cbs", "sfm", "chuncheon"],
  ["gangwon", "강원영동CBS 표준FM", "cbs", "sfm", "youngdong"],
  ["gangwon", "CBS JOY4U", "cbs", "joy4u"],
  ["gangwon", "FEBC 강원극동방송", "febc", undefined, "gangwon"],
  ["gangwon", "국방FM", "kookbang"],
  ["gangwon", "태백FM", "community", "taebaekfm"],

  ["jeju", "KBS제주 1라디오", "kbs", "1radio", "jeju"],
  ["jeju", "KBS제주 2라디오", "kbs", "2radio", "jeju"],
  ["jeju", "KBS제주 음악FM", "kbs", "1fm", "jeju"],
  ["jeju", "제주MBC 표준FM", "mbc", "sfm", "jeju"],
  ["jeju", "제주MBC FM4U", "mbc", "fm4u", "jeju"],
  ["jeju", "JIBS 뉴파워FM", "sbs", "powerfm", "jeju"],
  ["jeju", "EBS FM", "ebs", "fm"],
  ["jeju", "EBS 반디 외국어 전문", "ebs", "bandi"],
  ["jeju", "TBN 제주교통방송", "tbn", undefined, "jeju"],
  ["jeju", "제주CBS 표준FM", "cbs", "sfm", "jeju"],
  ["jeju", "CBS JOY4U", "cbs", "joy4u"],
  ["jeju", "FEBC 제주극동방송", "febc", undefined, "jeju"],
  ["jeju", "BBS 제주불교방송", "bbs", undefined, "jeju"],
  ["jeju", "국방FM", "kookbang"],
  ["jeju", "Arirang Radio", "arirang"],
];

function slug(value) {
  return value || "main";
}

export const CHANNELS = rawChannels.map(([regionId, name, stn, ch, city], index) => ({
  id: `${regionId}-${String(index + 1).padStart(3, "0")}-${stn}-${slug(ch)}-${slug(city)}`,
  regionId,
  name,
  stn,
  ch,
  city,
}));

export function getRegionName(regionId) {
  return REGIONS.find((region) => region.id === regionId)?.name || regionId;
}

